server {
    listen 80;
    server_name localhost;

    # Hexo 配置了 root: /blog/，静态资源都在 /blog/ 路径下
    location = / {
        return 301 /blog/;
    }

    location ^~ /blog/ {
        alias /usr/share/nginx/html/;
        index index.html;
    }
}
